### PR TITLE
Fix typos in german translation

### PR DESCRIPTION
**Pull request by mueller-ma**
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by mueller-ma** [comment]
@WangDaYeeeeee Can you merge this?

**Comment by connyduck** [comment]
Can this please be merged? The typos are really annoying. @WangDaYeeeeee

**Comment by mueller-ma** [comment]
@WangDaYeeeeee Any chance to get this merged? This typo is really annoying.

**Comment by mueller-ma** [comment]
Cleaning up my fork

**Pull request closed without merging**
